lib/raniulator_web/router.ex
defmodule RaniulatorWeb.Router do
  use RaniulatorWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {RaniulatorWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", RaniulatorWeb do
    pipe_through :browser
    resources "/roms", RomController do
      get "/body", RomController, :body
    end
    resources "/boxs", BoxController

    get "/", PageController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", RaniulatorWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: RaniulatorWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

lib/raniulator/application.ex
defmodule Raniulator.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  @impl true
  def start(_type, _args) do
    children = [
      # Start the Ecto repository
      Raniulator.Repo,
      # Start the Telemetry supervisor
      RaniulatorWeb.Telemetry,
      # Start the PubSub system
      {Phoenix.PubSub, name: Raniulator.PubSub},
      # Start the Endpoint (http/https)
      RaniulatorWeb.Endpoint,
      # Start a worker by calling: Raniulator.Worker.start_link(arg)
      # {Raniulator.Worker, arg}
      {Finch, name: DropboxClient}
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Raniulator.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  @impl true
  def config_change(changed, _new, removed) do
    RaniulatorWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/raniulator/mailer.ex
defmodule Raniulator.Mailer do
  use Swoosh.Mailer, otp_app: :raniulator
end

lib/raniulator/release.ex
defmodule Raniulator.Release do
  @moduledoc """
  Used for executing DB release tasks when run in production without Mix
  installed.
  """
  @app :raniulator

  def migrate do
    load_app()

    for repo <- repos() do
      {:ok, _, _} = Ecto.Migrator.with_repo(repo, &Ecto.Migrator.run(&1, :up, all: true))
    end
  end

  def rollback(repo, version) do
    load_app()
    {:ok, _, _} = Ecto.Migrator.with_repo(repo, &Ecto.Migrator.run(&1, :down, to: version))
  end

  defp repos do
    Application.fetch_env!(@app, :ecto_repos)
  end

  defp load_app do
    Application.load(@app)
  end
end

lib/raniulator/repo.ex
defmodule Raniulator.Repo do
  use Ecto.Repo,
    otp_app: :raniulator,
    adapter: Ecto.Adapters.Postgres
end

lib/raniulator/roms.ex
defmodule Raniulator.Roms do
  @moduledoc """
  The Roms context.
  """

  import Ecto.Query, warn: false

  @doc """
  Returns the list of roms.

  ## Examples

      iex> list_roms()
      [%Rom{}, ...]

  """
  def list_roms do
    Raniulator.Repo.all(Raniulator.Roms.Rom)
  end

  @doc """
  Gets a single rom.

  Raises `Ecto.NoResultsError` if the Rom does not exist.

  ## Examples

      iex> get_rom!(123)
      %Rom{}

      iex> get_rom!(456)
      ** (Ecto.NoResultsError)

  """
  def get_rom!(id), do: Raniulator.Repo.get!(Raniulator.Roms.Rom, id)

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking rom changes.

  ## Examples

      iex> change_rom(rom)
      %Ecto.Changeset{data: %Rom{}}

  """
  def change_rom(%Raniulator.Roms.Rom{} = rom, attrs \\ %{}) do
    Raniulator.Roms.Rom.changeset(rom, attrs)
  end

  @doc """
  Creates a rom.

  ## Examples

      iex> create_rom(%{field: value})
      {:ok, %Rom{}}

      iex> create_rom(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_rom(attrs \\ %{}) do
    %Raniulator.Roms.Rom{}
    |> Raniulator.Roms.Rom.changeset(attrs)
    |> Raniulator.Repo.insert()
  end
end

lib/raniulator/roms/rom.ex
defmodule Raniulator.Roms.Rom do
  use Ecto.Schema
  import Ecto.Changeset

  @primary_key {:id, :binary_id, autogenerate: true}
  @foreign_key_type :binary_id
  schema "roms" do
    field :name, :string
    field :body, :binary
    field :hash, :string

    timestamps()
  end

  @doc false
  def changeset(rom, attrs) do
    rom
    |> cast(attrs, [:name, :body, :hash])
    |> validate_required([:name, :body, :hash])
    |> unique_constraint([:name, :hash])
  end
end

lib/raniulator_web/controllers/box_controller.ex
defmodule RaniulatorWeb.BoxController do
  use RaniulatorWeb, :controller

  def create(conn, %{"box" => %{"link" => link}}) do

    DropboxClient.pull_files(link)

    conn
    |> put_flash(:info, "Box imported, enjoy.")
    |> redirect(to: Routes.rom_path(conn, :index))
  end
end

lib/raniulator_web/controllers/page_controller.ex
defmodule RaniulatorWeb.PageController do
  use RaniulatorWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end
end

lib/raniulator_web/controllers/rom_controller.ex
defmodule RaniulatorWeb.RomController do
  use RaniulatorWeb, :controller
  def index(conn, _params) do
    roms = Raniulator.Roms.list_roms()
    render(conn, "index.html", roms: roms)
  end
  def create(conn, %{"rom" => rom_params}) do
    case Raniulator.Roms.create_rom(rom_params) do
      {:ok, rom} ->
        conn
        |> put_flash(:info, "Rom created successfully.")
        |> redirect(to: Routes.rom_path(conn, :show, rom))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  @spec show(Plug.Conn.t(), map) :: Plug.Conn.t()
  def show(conn, %{"id" => id}) do
    render(conn, "show.html", rom: Raniulator.Roms.get_rom!(id))
  end

  @spec body(Plug.Conn.t(), map) :: Plug.Conn.t()
  def body(conn, %{"rom_id" => rom_id}) do
    send_resp(conn, 200, Raniulator.Roms.get_rom!(rom_id).body)
  end
end

lib/raniulator_web/views/error_view.ex
defmodule RaniulatorWeb.ErrorView do
  use RaniulatorWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/raniulator_web/views/layout_view.ex
defmodule RaniulatorWeb.LayoutView do
  use RaniulatorWeb, :view

  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  @compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}
end

lib/raniulator_web/views/page_view.ex
defmodule RaniulatorWeb.PageView do
  use RaniulatorWeb, :view
end

lib/raniulator_web/views/rom_view.ex
defmodule RaniulatorWeb.RomView do
  use RaniulatorWeb, :view
end

lib/raniulator_web/templates/layout/app.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

lib/raniulator_web/templates/layout/live.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

lib/raniulator_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tag() %>
    <%= live_title_tag assigns[:page_title] || "Raniulator" %>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")}/>
    <script type="text/javascript" src="https://unpkg.com/jsnes/dist/jsnes.min.js"></script>
    <script defer phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/assets/app.js")}></script>
  </head>
  <body>
    <header>
      <section class="container">
        <nav>
          <ul>
            <li><%= link "Upload", to: Routes.page_path(@conn, :index) %></li>
            <li><%= link "ROMs", to: Routes.rom_path(@conn, :index) %></li>
            <%= if function_exported?(Routes, :live_dashboard_path, 2) do %>
              <li><%= link "LiveDashboard", to: Routes.live_dashboard_path(@conn, :home) %></li>
            <% end %>
          </ul>
        </nav>
      </section>
    </header>
    <%= @inner_content %>
  </body>
</html>

lib/raniulator_web/templates/page/index.html.heex
<section class="phx-hero">
  <h1><%= gettext "Welcome to %{name}!", name: "Raniulator" %></h1>
</section>

<section class="row">
  <article class="column">
    <p>
      Use your special dropbox link.
    </p>
    <%= form_for @conn, Routes.box_path(@conn, :create), [as: :box], fn f -> %>
      <%= label f, :link %>
      <%= text_input f, :link %>
      <%= error_tag f, :link %>

      <%= submit "Submit" %>
    <% end %>
  </article>
</section>

lib/raniulator_web/templates/rom/index.html.heex
<h1>Listing Roms</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Url</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for rom <- @roms do %>
    <tr>
      <td><%= rom.name %></td>
      <td>
        <span><%= link "Show", to: Routes.rom_path(@conn, :show, rom) %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

lib/raniulator_web/templates/rom/show.html.heex
<script type="text/javascript">
  window.onload = function() {
    window.nes_load_url("nes-canvas", "<%= Routes.rom_rom_path(@conn, :body, @rom) %>");
  }
</script>

<div style="margin: auto; width: 85%;">
  <canvas id="nes-canvas" width="256" height="240" style="width: 100%"/>
</div>
<p>
  DPad: Arrow keys<br/>Start: Return, Select: Tab<br/>A Button: A, B Button: S
</p>